/*
 * Copyright 2014-2026 Netflix, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.netflix.atlas.pekko

import java.util.concurrent.ThreadLocalRandom
import java.util.concurrent.atomic.AtomicReference
import scala.concurrent.ExecutionContext
import scala.concurrent.Future
import scala.util.Failure
import com.netflix.atlas.json3.Json
import com.netflix.spectator.ipc.NetflixHeader
import org.apache.pekko.http.scaladsl.model.AttributeKey
import org.apache.pekko.http.scaladsl.model.HttpHeader
import org.apache.pekko.http.scaladsl.model.HttpMethods
import org.apache.pekko.http.scaladsl.model.HttpRequest
import org.apache.pekko.http.scaladsl.model.HttpResponse
import org.apache.pekko.http.scaladsl.model.MediaType
import org.apache.pekko.http.scaladsl.model.StatusCodes
import org.apache.pekko.http.scaladsl.model.headers.*
import org.apache.pekko.http.scaladsl.server.Directive
import org.apache.pekko.http.scaladsl.server.Directive0
import org.apache.pekko.http.scaladsl.server.Directive1
import org.apache.pekko.http.scaladsl.server.Directives.*
import org.apache.pekko.http.scaladsl.server.MalformedRequestContentRejection
import org.apache.pekko.http.scaladsl.server.PathMatcher
import org.apache.pekko.http.scaladsl.server.Route
import org.apache.pekko.http.scaladsl.server.RouteResult
import org.apache.pekko.http.scaladsl.server.directives.LoggingMagnet
import org.apache.pekko.http.scaladsl.server.util.Tuple
import org.apache.pekko.http.scaladsl.unmarshalling.FromRequestUnmarshaller
import org.apache.pekko.stream.Materializer
import org.apache.pekko.util.ByteString
import tools.jackson.core.JsonParser
import tools.jackson.module.scala.JavaTypeable
import scala.util.Success

object CustomDirectives {

  private val endpointHeaderName = NetflixHeader.Endpoint.headerName()

  /**
    * Request attribute used to propagate the matched endpoint from the `endpointPath*`
    * directives out to the `accessLog` directive. The value is a mutable holder that is
    * populated while the request path is being matched. This allows the endpoint to be
    * recorded even if the inner route throws an exception or is rejected: in those cases
    * the response is generated by an error handler that is wrapped outside of the
    * `endpointPath*` directive, so the `Netflix-Endpoint` header set on the way out would
    * otherwise be lost and the access log would fall back to a sanitized request path.
    */
  private val endpointAttr = AttributeKey[AtomicReference[String]]("atlas-endpoint")

  /**
    * Request attribute holding the mutable slot used to propagate the caller established by a
    * `RequestAuthenticator` (via [[recordCaller]]) out to the `accessLog` directive. Uses the
    * same holder pattern as [[endpointAttr]] so the caller is available on the access log even
    * though the authenticator runs inside the access log wrapper.
    */
  private val callerAttr = AttributeKey[AtomicReference[CallerContext]]("atlas-caller-holder")

  private def isSmile(mediaType: MediaType): Boolean = {
    mediaType == CustomMediaTypes.`application/x-jackson-smile`
  }

  /**
    * Used with `parseEntity` to decode the request entity to an object of type
    * `T` using the default ObjectMapper from `atlas-json`. If the content type
    * is `application/x-jackson-smile`, then a smile parser will be used. Otherwise
    * it will be treated as `application/json` regardless of the content type.
    *
    * Note: This is kept as a separate function passed into the `parseEntity`
    * directive because adding the manifest to `T` causes problems when used
    * directly on the directive. It also makes it possible to reuse `parseEntity`
    * with a custom function.
    */
  def json[T: JavaTypeable]: MediaType => ByteString => T = { mediaType => bs =>
    {
      if (isSmile(mediaType))
        Json.smileDecode[T](ByteStringInputStream.create(bs))
      else
        Json.decode[T](ByteStringInputStream.create(bs))
    }
  }

  /**
    * Used with `parseEntity` to decode the request entity to an object of type
    * `T` using a custom decoder function. If the content type is
    * `application/x-jackson-smile`, then a smile parser will be used. Otherwise
    * it will be treated as `application/json` regardless of the content type.
    */
  def customJson[T](decoder: JsonParser => T): MediaType => ByteString => T = { mediaType => bs =>
    {
      val p =
        if (isSmile(mediaType))
          Json.newSmileParser(ByteStringInputStream.create(bs))
        else
          Json.newJsonParser(ByteStringInputStream.create(bs))
      try decoder(p)
      finally p.close()
    }
  }

  /**
    * Parses the request entity into an object of type `T`. The parsing is done by
    * passing in the complete request data to the function `f`.
    */
  def parseEntity[T](f: MediaType => ByteString => T): Directive1[T] = {
    extractRequestContext.flatMap[Tuple1[T]] { ctx =>
      import ctx.executionContext
      import ctx.materializer
      val entity = ctx.request.entity
      val future = entity.dataBytes.runReduce(_ ++ _).map(f(entity.contentType.mediaType))
      onComplete(future).flatMap {
        case Success(v) => provide[T](v)
        case Failure(t) => reject(MalformedRequestContentRejection("invalid request payload", t))
      }
    }
  }

  /**
    * Used with `entity` to decode the request entity to an object of type
    * `T` using the default ObjectMapper from `atlas-json`. If the content type
    * is `application/x-jackson-smile`, then a smile parser will be used. Otherwise
    * it will be treated as `application/json` regardless of the content type.
    */
  def jsonUnmarshaller[T: JavaTypeable]: FromRequestUnmarshaller[T] = {
    val parse = json[T]
    new FromRequestUnmarshaller[T] {
      override def apply(
        request: HttpRequest
      )(implicit ec: ExecutionContext, materializer: Materializer): Future[T] = {
        val entity = request.entity
        entity.dataBytes.runReduce(_ ++ _).map(parse(entity.contentType.mediaType))
      }
    }
  }

  /**
    * Extract the [[CallerContext]] that was populated by a [[RequestAuthenticator]]. If no
    * authenticator is configured, or it did not set the context, then the anonymous context
    * is provided. This allows endpoints to depend on the caller identity without a compile
    * time dependency on the mechanism used to establish it.
    */
  def extractCaller: Directive1[CallerContext] = {
    optionalAttribute(CallerContext.attr).map(_.getOrElse(CallerContext.Anonymous))
  }

  /**
    * Record the caller established by a [[RequestAuthenticator]] so that it is available to the
    * inner routes via [[extractCaller]] and to the access log. It both sets the [[CallerContext]]
    * request attribute (read by `extractCaller`) and, when present, populates the holder installed
    * by `accessLog` so the caller is logged even though the authenticator runs inside it.
    */
  def recordCaller(caller: CallerContext): Directive0 = {
    optionalAttribute(callerAttr).flatMap { holder =>
      holder.foreach(_.set(caller))
      mapRequest(_.addAttribute(CallerContext.attr, caller))
    }
  }

  // Make sure that all headers in the response will be readable by the browser
  private def exposeHeaders: Directive0 = {
    mapResponseHeaders { headers =>
      val exposed = headers.map(_.name).filterNot(_.startsWith("Access-Control"))
      if (exposed.isEmpty) headers
      else {
        headers ++ scala.collection.immutable.Seq(`Access-Control-Expose-Headers`(exposed))
      }
    }
  }

  /**
    * Filter to provide basic CORS support. By default it assumes that actual security is provided
    * elsewhere. The goal for this filter is to allow javascript UIs or other tools to access
    * the APIs and work with minimal fuss.
    *
    * The hosts param specifies a whitelist for allowing cross-origin requests. Default is no
    * requests will get CORS headers.
    */
  def respondWithCorsHeaders(hosts: List[String] = Nil): Directive0 = {

    // Add the cors headers to anything with an origin, browser behavior seems to be mixed as to
    // which request headers we can expect to receive
    optionalHeaderValueByName("Origin").flatMap {
      case None                                                 => pass
      case Some(origin) if !Cors.isOriginAllowed(hosts, origin) => pass
      case Some(origin)                                         =>
        // '*' doesn't seem to work reliably so use requested origin if provided. If running from
        // a local file we typically see 'null'.
        val allow =
          if (origin == "null") HttpOriginRange.`*` else HttpOriginRange(HttpOrigin(origin))

        // List of headers to ignore for caching. For more details see:
        // https://bugs.chromium.org/p/chromium/issues/detail?id=409090
        // https://www.fastly.com/blog/caching-cors
        val vary = RawHeader("Vary", "Origin")

        // Just allow all methods
        val headers = List(
          `Access-Control-Allow-Origin`.forRange(allow),
          `Access-Control-Allow-Methods`(
            HttpMethods.GET,
            HttpMethods.PATCH,
            HttpMethods.POST,
            HttpMethods.PUT,
            HttpMethods.DELETE
          ),
          `Access-Control-Allow-Credentials`(true),
          vary
        )

        // If specific headers are requested echo those back
        optionalHeaderValueByName("Access-Control-Request-Headers").flatMap {
          case None =>
            respondWithHeaders(headers) & exposeHeaders
          case Some(h) =>
            val finalHeaders = `Access-Control-Allow-Headers`(h) :: headers
            respondWithHeaders(finalHeaders) & exposeHeaders
        }
    }
  }

  /** Route for CORS handling pre-flight checks. */
  def corsPreflight(hosts: List[String] = Nil): Route = {
    // Set max age header to minimize the number of round-trips the browser will need
    // to make. Various browsers limit the max age that can be used. Ten minutes seems
    // to be a common number (chrome and webkit) so that is what we use here.
    val response = HttpResponse(StatusCodes.OK).withHeaders(`Access-Control-Max-Age`(600))

    // Assume all OPTIONS requests are for pre-flight checks
    options {
      extractRequestContext { ctx =>
        // For some requests the browser wants the CORS headers to be present on the
        // pre-flight response.
        respondWithCorsHeaders(hosts) {
          // Ignore request body if present
          val future = ctx.request.discardEntityBytes(ctx.materializer).future()
          onComplete(future) { _ =>
            complete(response)
          }
        }
      }
    }
  }

  /**
    * Wraps a route with support for CORS. This will handle the preflight checks as well
    * as adding the appropriate headers to the response of the inner route.
    */
  def cors(hosts: List[String])(inner: Route): Route = {
    corsPreflight(hosts) ~ respondWithCorsHeaders(hosts) { inner }
  }

  // Helper function to finish constructing the log entry and writing to the logger. The caller
  // holder is read at completion time so that an identity recorded by an inner authenticator is
  // applied to the log entry.
  private def log(
    logger: AccessLogger,
    caller: AtomicReference[CallerContext]
  )(req: HttpRequest)(result: RouteResult): Unit = {
    logger.withCaller(caller.get())
    result match {
      case RouteResult.Complete(res) => logger.complete(req, Success(res))
      case RouteResult.Rejected(vs)  => logger.complete(req, Failure(new Exception(vs.toString)))
    }
  }

  /**
    * Generate an access log using spectator HttpLogEntry utility.
    *
    * @param headers
    *     Additional headers to apply to the response before passing to the logger. This
    *     is intended for providing additional context such as the server group and zone
    *     of the particular server instance with common IPC.
    */
  def accessLog(headers: List[HttpHeader]): Directive0 = {
    extractClientIP.flatMap { ip =>
      val addr = ip.toOption.fold("unknown")(_.getHostAddress)
      val entry = AccessLogger.ipcLogger.createServerEntry.withRemoteAddress(addr)
      val logger = AccessLogger.newServerLogger(entry)

      // Holders for values recorded by inner directives while the request is handled, so they
      // can still be applied to the access log even when the response is produced by an error
      // handler (exception or rejection) that runs outside the recording directive's scope.
      // `endpoint` is set by the `endpointPath*` directives; `caller` is set by a
      // `RequestAuthenticator` via `recordCaller`. Both run inside this `accessLog` wrapper.
      // Note the ordering: `logRequestResult` must wrap `addRecordedEndpointHeader` so that the
      // logged response reflects the endpoint header that was added.
      val endpoint = new AtomicReference[String]()
      val caller = new AtomicReference[CallerContext](CallerContext.Anonymous)
      mapRequest(_.addAttribute(endpointAttr, endpoint).addAttribute(callerAttr, caller)) &
        logRequestResult(LoggingMagnet(_ => log(logger, caller))) &
        addRecordedEndpointHeader(endpoint) &
        respondWithDefaultHeaders(headers)
    }
  }

  // Ensures the `Netflix-Endpoint` header is present on the response using the endpoint
  // recorded while matching the request path. `withDefaultHeaders` is a no-op if the
  // header was already added by the `endpointPath*` directive (the normal success case).
  //
  // This fallback is only applied to error responses. A successful response either came
  // from an `endpointPath*` route (which already set the header) or from a route that has
  // no endpoint, so it should not be attributed to a recorded endpoint. Restricting to
  // failures also avoids applying a stale recording: an `endpointPath*` prefix may match
  // and record its endpoint but then have its inner route rejected and backtracked, after
  // which a sibling route completes the request; that sibling response must not inherit
  // the rejected prefix's endpoint.
  private def addRecordedEndpointHeader(endpoint: AtomicReference[String]): Directive0 = {
    mapResponse { response =>
      val value = endpoint.get()
      if (value == null || !response.status.isFailure())
        response
      else
        response.withDefaultHeaders(RawHeader(endpointHeaderName, value))
    }
  }

  /**
    * Adds the `Netflix-Endpoint` header to the response if it is not already present. This
    * directive is typically not used directly, it is preferred to use one of the `endpointPath*`
    * directives instead.
    */
  def respondWithEndpointHeader: Directive0 = {
    extractMatchedPath.flatMap { path =>
      val value = path.toString()
      // Record the endpoint so that it can still be applied by `accessLog` if the inner
      // route throws an exception or is rejected. The header is also added directly for
      // the common case where the inner route completes normally.
      recordEndpoint(value).tflatMap { _ =>
        respondWithDefaultHeader(RawHeader(endpointHeaderName, value))
      }
    }
  }

  // Store the matched endpoint in the holder installed by `accessLog`, if present. This
  // is done while matching the request path so the value survives even when the inner
  // route does not produce a response directly (exception or rejection). Later, deeper
  // matches overwrite earlier ones so the most specific endpoint is used, consistent
  // with the behavior of the `Netflix-Endpoint` header.
  private def recordEndpoint(value: String): Directive0 = {
    // Use the `optionalAttribute` directive rather than `request.attribute(...)`: the
    // latter resolves a deprecated implicit (JavaMapping.attributeKey) that will no
    // longer be found in Scala 3.10.
    optionalAttribute(endpointAttr).flatMap { holder =>
      holder.foreach(_.set(value))
      pass
    }
  }

  /**
    * Alternative to the built-in `path` directive that will set the `Netflix-Endpoint` header
    * based on the currently matched path. To avoid matching paths with arbitrary values that
    * should not be a part of the header, the path matcher is restricted so that values cannot
    * be extracted. Use `endpointPathPrefix` with a nested `path` directive for those use-cases.
    */
  def endpointPath(pm: PathMatcher[Unit]): Directive0 = {
    path(pm).tflatMap { _ =>
      respondWithEndpointHeader
    }
  }

  /**
    * This is a convenience directive for the common pattern of having a fixed path with an
    * extracted portion such as an identifier at the end. It will set the endpoint header based
    * on the prefix matcher. Example:
    *
    * ```
    * endpointPathPrefix("api" / "v1" / "instances") {
    *   path(Remaining) { id =>
    *     ...
    *   }
    * }
    * ```
    *
    * Can instead be written as:
    *
    * ```
    * endpointPath("api" / "v1" / "instances", Remaining) { id =>
    *   ...
    * }
    * ```
    */
  def endpointPath[L](prefix: PathMatcher[Unit], remaining: PathMatcher[L]): Directive[L] = {
    implicit val evidence: Tuple[L] = remaining.ev
    endpointPathPrefix(prefix).tflatMap { _ =>
      path(remaining)
    }
  }

  /**
    * Alternative to the built-in `pathPrefix` directive that will set the `Netflix-Endpoint`
    * header based on the currently matched path. To avoid matching paths with arbitrary values
    * that should not be a part of the header, the path matcher is restricted so that values cannot
    * be extracted.
    */
  def endpointPathPrefix(pm: PathMatcher[Unit]): Directive0 = {
    pathPrefix(pm).tflatMap { _ =>
      respondWithEndpointHeader
    }
  }

  /**
    * Add connection close header to some responses. This can be useful when using
    * network load balancers to allow some connection reuse, but force connections
    * to close frequently enough to ensure that traffic balances across instances.
    *
    * @param probability
    *     A value of 0.0 means it will never be added, 1.0 means it will
    *     always be added.
    */
  def closeConnection(probability: Double): Directive0 = {
    val closeHeader = Connection("close")

    if (probability <= 0.0) {
      // Nothing to do
      pass
    } else if (probability >= 1.0) {
      // Always close, no need to bother checking
      respondWithHeader(closeHeader)
    } else {
      mapResponseHeaders { headers =>
        val random = ThreadLocalRandom.current()
        if (random.nextDouble() < probability)
          headers.prepended(closeHeader)
        else
          headers
      }
    }
  }
}
