import sbt._

object Dependencies {
  val akkaActor       = "com.typesafe.akka" % "akka-actor_2.11" % "2.3.6"
  val akkaSlf4j       = "com.typesafe.akka" % "akka-slf4j_2.11" % "2.3.6"
  val akkaTestkit     = "com.typesafe.akka" % "akka-testkit_2.11" % "2.3.6"
  val awsJavaSdk      = "com.amazonaws" % "aws-java-sdk" % "1.9.3"
  val frigga          = "com.netflix.frigga" % "frigga" % "0.13"
  val guava           = "com.google.guava" % "guava" % "14.0.1"
  val hadoopCommon    = "org.apache.hadoop" % "hadoop-common" % "2.5.1"
  val jacksonAnno2    = "com.fasterxml.jackson.core" % "jackson-annotations" % "2.4.3"
  val jacksonCore2    = "com.fasterxml.jackson.core" % "jackson-core" % "2.4.3"
  val jacksonJoda2    = "com.fasterxml.jackson.datatype" % "jackson-datatype-joda" % "2.4.3"
  val jacksonMapper2  = "com.fasterxml.jackson.core" % "jackson-databind" % "2.4.3"
  val jacksonScala2   = "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.4.3"
  val jacksonSmile2   = "com.fasterxml.jackson.dataformat" % "jackson-dataformat-smile" % "2.4.3"
  val jna             = "net.java.dev.jna" % "jna" % "4.1.0"
  val jodaConvert     = "org.joda" % "joda-convert" % "1.7"
  val jodaTime        = "joda-time" % "joda-time" % "2.5"
  val log4j           = "log4j" % "log4j" % "1.2.17"
  val luceneCore      = "org.apache.lucene" % "lucene-core" % "4.10.2"
  val luceneQueries   = "org.apache.lucene" % "lucene-queries" % "4.10.2"
  val luceneRegex     = "org.apache.lucene" % "lucene-sandbox" % "4.10.2"
  val pegdown         = "org.pegdown" % "pegdown" % "1.4.2"
  val ribbonTransport = "com.netflix.ribbon" % "ribbon-transport" % "2.0-RC9"
  val scalaLibrary    = "org.scala-lang" % "scala-library" % "2.11.4"
  val scalaLibraryAll = "org.scala-lang" % "scala-library-all" % "2.11.4"
  val scalaLogging    = "com.typesafe.scala-logging" % "scala-logging_2.11" % "3.1.0"
  val scalaParsec     = "org.scala-lang.modules" % "scala-parser-combinators_2.11" % "1.0.2"
  val scalaReflect    = "org.scala-lang" % "scala-reflect" % "2.11.4"
  val scalatest       = "org.scalatest" % "scalatest_2.11" % "2.2.1"
  val servoCore       = "com.netflix.servo" % "servo-core" % "0.7.9"
  val slf4jApi        = "org.slf4j" % "slf4j-api" % "1.7.7"
  val slf4jLog4j      = "org.slf4j" % "slf4j-log4j12" % "1.7.7"
  val slf4jSimple     = "org.slf4j" % "slf4j-simple" % "1.7.7"
  val snmp4j          = "org.snmp4j" % "snmp4j" % "2.3.0"
  val spectatorApi    = "com.netflix.spectator" % "spectator-api" % "0.14.1"
  val spectatorM2     = "com.netflix.spectator" % "spectator-reg-metrics2" % "0.14.1"
  val spectatorNflx   = "com.netflix.spectator" % "spectator-nflx" % "0.14.1"
  val sprayCan        = "io.spray" % "spray-can_2.11" % "1.3.2"
  val sprayClient     = "io.spray" % "spray-client_2.11" % "1.3.2"
  val sprayRouting    = "io.spray" % "spray-routing_2.11" % "1.3.2"
  val sprayTestkit    = "io.spray" % "spray-testkit_2.11" % "1.3.2"
  val trove           = "net.sf.trove4j" % "trove4j" % "3.0.3"
  val typesafeConfig  = "com.typesafe" % "config" % "1.2.1"
}
