name: Snapshot

on:
  push:
    branches:
      - main
      - v[0-9]+.[0-9]+.x

jobs:
  build:
    if: ${{ github.repository == 'Netflix/atlas' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'sbt'
      - name: SetupPGP
        run: echo $ORG_SIGNING_KEY | sed -r 's/-----[^-]+-----//g;s/\n//g;s/ //g' | base64 --decode | gpg --batch --import
        env:
          ORG_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
      - name: Build
        env:
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
          NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
          NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.ORG_SIGNING_PASSWORD }}
        run: |
          git fetch --unshallow --tags
          cat /dev/null | project/sbt ++2.13.16 clean test +publishSigned
