name: Snapshot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
          key: ${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
      - name: SetupPGP
        run: echo $ORG_SIGNING_KEY | sed -r 's/-----[^-]+-----//g;s/\n//g;s/ //g' | base64 --decode | gpg --batch --import
        env:
          ORG_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
      - name: Build
        env:
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
          NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
          NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.ORG_SIGNING_PASSWORD }}
        run: |
          git fetch --unshallow --tags
          cat /dev/null | project/sbt clean test +publishSigned
